version: "3.8"

services:
  localstack:
    image: 'localstack/localstack'
    container_name: 'localstack'
    restart: always
    environment:
      - SERVICES=ssm,sqs,s3
      - DEFAULT_REGION=ap-southeast-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566:4566'
    volumes:
      - "${HOME}/localstack_volume:/var/lib/localstack"